### ISSUE TITLE
Review base122 encoding

### ISSUE THREAD

**Issue by salteadorneo** [salteadorneo/PlayJS#22]

**Comment by piguicorn** [comment]
El único codificador base122 para JavaScript que encuentro es el de Kevin Alberston (https://github.com/kevinAlbs/Base122) que es un poco difícil de usar ya que está pensado para Node.js y tiene un poco de tiempo. 

Además no sé si puede ser un cambio tan significativo como para prestarle atención. Igual se pueden valorar otras soluciones.
