### ISSUE TITLE
Add contribute link to playground page

### ISSUE THREAD

**Issue by piguicorn** [salteadorneo/PlayJS#39]
It could be nice to add a link to the playground page that takes to the "How to contribute" markdown file. Maybe the bottom menu.

![highlight of the bottom menu in PlayJS](https://github.com/salteadorneo/PlayJS/assets/39622540/28136aa4-b8cb-4168-8751-ecbfd5a20e2e)

**Comment by harshk461** [comment]
I want to contribute to this
